# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - hgyygygnfnfdocker

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_80a351fdb05d435db72c31425f312229 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d8f4e2ae3984491a8ae4e94faecbddee }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_80a351fdb05d435db72c31425f312229 }}/nginx:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hgyygygnfnfdocker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c83ae54e868f4cf6a79149c96289bd49 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_80a351fdb05d435db72c31425f312229 }}/nginx:${{ github.sha }}'